---
# create-asg/tasks/main.yml

- name: Create Auto Scaling Group
  ec2_asg:
      name: "webapp-asg-{{ fact_time }}"
      region: "{{ region }}"
      load_balancers:
          - "webapp-elb-{{ fact_time }}"
          #- "webapp-elb-20151113111832"
      availability_zones: "{{ zone }}"
      launch_config_name: "webapp-lc-{{ fact_time }}"
      health_check_type: ELB
      health_check_period: 300
      default_cooldown: 180
      min_size: 3
      max_size: 5
      desired_capacity: 3
      state: present
      tags:
          - env: "{{ instance_tag_env }}"
  register: asg_result
  tags: [asg]

#- name: debug output for asg result
#  debug: var=asg_result
#  tags: [asg]

- name: Create ASG scale up policy
  ec2_scaling_policy:
      state: present
      region: "{{ region }}"
      name: "webapp-asg-policy-scale-up"
      asg_name: "webapp-asg-{{ fact_time }}"
      adjustment_type: "ChangeInCapacity"
      scaling_adjustment: +1
      min_adjustment_step: 1
      cooldown: 60
  register: sp_up_result
  tags: [asg]

#- name: debug output for policy result
#  debug: var=sp_up_result
#  tags: [asg]

- name: Create ASG scale down policy
  ec2_scaling_policy:
      state: present
      region: "{{ region }}"
      name: "webapp-asg-policy-scale-down"
      asg_name: "webapp-asg-{{ fact_time }}"
      adjustment_type: "ChangeInCapacity"
      scaling_adjustment: -1
      min_adjustment_step: 1
      cooldown: 60
  register: sp_down_result
  tags: [asg]

- name: Configure scale up metric alarm and link to scaling policy
  ec2_metric_alarm:
    region: "{{ region }}"
    name: "webapp-metric-alarm-scale-up"
    state: present
    metric: "CPUUtilization"
    namespace: "AWS/EC2"
    statistic: "Average"
    comparison: ">="
    threshold: 50.0
    period: 60
    evaluation_periods: 1
    unit: "Percent"
    dimensions:
      AutoScalingGroupName: webapp-asg-{{ fact_time }}
    alarm_actions: ["{{ sp_up_result.arn }}"]
  tags: [asg]

- name: Configure scale down metric alarm and link to scaling policy
  ec2_metric_alarm:
    region: "{{ region }}"
    name: "webapp-metric-alarm-scale-down"
    state: present
    metric: "CPUUtilization"
    namespace: "AWS/EC2"
    statistic: "Average"
    comparison: "<="
    threshold: 20.0
    period: 60
    evaluation_periods: 1
    unit: "Percent"
    dimensions:
      AutoScalingGroupName: webapp-asg-{{ fact_time }}
    alarm_actions: ["{{ sp_down_result.arn }}"]
  tags: [asg]
