---
# create-elb/tasks/main.yml

- name: Configure Elastic Load Balancers
  local_action:
    module: ec2_elb_lb
    region: "{{ region }}"
    name: "webapp-elb-{{ fact_time }}"
    state: present
    zones: "{{ zone }}"
    security_group_names: "{{ security_groups }}"
    connection_draining_timeout: 300
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
    health_check:
      ping_protocol: http
      ping_port: 80
      ping_path: "/"
      response_timeout: 10
      interval: 30
      unhealthy_threshold: 6
      healthy_threshold: 2
  register: elb_result

- name: debug output for elb_result
  debug: var=elb_result
