---
# create-lc/tasks/main.yml

- name: Create Launch Configuration
  local_action:
    module: ec2_lc
    region: "{{ region }}"
    name: "webapp-lc-{{ fact_time }}"
    image_id: "{{ ami.image_id }}"
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_type }}"
    security_groups: "{{ security_groups }}"
    instance_monitoring: yes
