---
# install-nginx/tasks/main.yml

- name: ensure /var/www exists and is owned by root
  file: path=/var/www state=directory owner=root group=root mode=0755
  tags: [var-www-root]

- name: Update the apt-get cache
  apt: update_cache=yes

- name: Install packages
  action: apt pkg={{ item }} state=installed
  with_items:
    - nginx-extras
    - nginx-common
  tags: [nginx, php]

- name: ensure nginx will start at boot
  service: name=nginx enabled=yes
  tags: [nginx]

- name: start nginx
  service: name=nginx state=started
  tags: [nginx]
